---
name: TVHeadend
version: dev
slug: tvheadend
description: TV streaming server and recorder.
url: "https://github.com/dfigus/addon-tvheadend"
ingress: true
ingress_stream: true
init: false
panel_icon: mdi:television
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
devices:
  - /dev/dvb
  - /dev/dri
  - /dev/vcsm-cma
  - /dev/vchiq
ports:
  9981/tcp: 9981
  9982/tcp: 9982
ports_description:
  9981/tcp: TVH Web Interface
  9982/tcp: TVH HTSP
map:
  - addon_config:rw
  - share:rw
  - media:rw
options:
  system_packages: []
  init_commands: []
  args: ""
  comskip_ini: ""
schema:
  system_packages:
    - str?
  init_commands:
    - str?
  args: str?
  comskip_ini: str?
