---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: read
  packages: read
  contents: write
  pull-requests: read
  security-events: write

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/app-ci.yaml@6fc3bc2b7ad4b7ae3dcf68d644d6e3a792eda831
