---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@6fc3bc2b7ad4b7ae3dcf68d644d6e3a792eda831
